apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    name: pgadmin-service
    app: pgadmin
spec:
  ports:
  - port: 80
    targetPort: 80
    name: pgadmin-http
  - port: 443
    targetPort: 443
    name: pgadmin-https
  type: LoadBalancer 
  selector:
    name: pgadmin-pod
    app: pgadmin